"""Version information for lobster package."""
# This file is automatically generated by setuptools-scm
# Do not edit manually
__version__ = "0.0.0"  # Placeholder, will be replaced by setuptools-scm
